[SSoC 2.0] Adding Readme for Frontend Projects
Vikash-8090-Yadav/Future.WebNet pull request #493
Opened 2023-07-28 18:40 UTC by Avdhesh-Varshney

Added Readme for Front end projects

Issue Number - 348

close issue #348

2023-07-28 18:40 UTC, Avdhesh-Varshney commented
@shubhisingh184 @Vikash-8090-Yadav sir, please review this pr

2023-07-29 13:09 UTC, shubhisingh184 commented
@Avdhesh-Varshney there's a project music shop is removed, so update that.

2023-07-29 14:06 UTC, Avdhesh-Varshney commented
@shubhisingh184 @Vikash-8090-Yadav please again review this pr

2023-07-29 16:39 UTC, Vikash-8090-Yadav requested changes
Do the necessary  changes.

2023-07-29 16:39 UTC, Vikash-8090-Yadav commented on Frontend-Projects/README.md
> +    <img src="https://readme-typing-svg.herokuapp.com?color=45ffaa&size=40&width=900&height=80&lines=Welcome-to-the-World-of-Web3🚀"/>
it should be `Welcome-to-the-World-of-WebDev`

2023-07-29 16:53 UTC, Avdhesh-Varshney commented
> Do the necessary changes.

@Vikash-8090-Yadav @shubhisingh184 please again review this pr

2023-07-30 10:35 UTC, merged